apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
data:
  alerting.yaml: |
    apiVersion: 1

    contactPoints:
      - orgId: 1
        name: notifier-webhook
        receivers:
          - uid: notifier-webhook-uid
            type: webhook
            settings:
              url: http://notifier:9000/webhook/grafana
              httpMethod: POST

    policies:
      - orgId: 1
        receiver: notifier-webhook
        group_by: ['alertname']

    groups:
      - orgId: 1
        name: ddos-detekcija
        folder: DDoS Detekcija
        interval: 15s
        rules:
          - uid: ddos-napad-aktivan
            title: "DDoS napad detektovan"
            condition: C
            for: 10s
            noDataState: NoData
            execErrState: Error
            labels: {}
            annotations:
              summary: "Detektovan je DDoS napad na target servis"
            data:
              - refId: A
                relativeTimeRange:
                  from: 60
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: max(detection_verdict{verdict_type=~"http_flood|slowpost"})
                  instant: true
                  refId: A
              - refId: C
                datasourceUid: __expr__
                model:
                  type: threshold
                  expr: ""
                  conditions:
                    - evaluator:
                        type: gt
                        params: [0]
                      operator:
                        type: and
                      query:
                        params: ["A"]
                      reducer:
                        type: last
                  refId: C
          - uid: ddos-detekcija-nesigurna
            title: "Detekcija nesigurna"
            condition: C
            for: 10s
            noDataState: NoData
            execErrState: Error
            labels: {}
            annotations:
              summary: "Detekcija ne moze pouzdano da odredi da li je napad aktivan"
            data:
              - refId: A
                relativeTimeRange:
                  from: 60
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: max(detection_verdict{verdict_type="unknown"})
                  instant: true
                  refId: A
              - refId: C
                datasourceUid: __expr__
                model:
                  type: threshold
                  expr: ""
                  conditions:
                    - evaluator:
                        type: gt
                        params: [0]
                      operator:
                        type: and
                      query:
                        params: ["A"]
                      reducer:
                        type: last
                  refId: C