services: # vrste kontejnera, ne pojedinacna instanca
  c2:
    build: ./c2
    ports:
      - "5001:5001"

  bot:
    build: ./attacker
    depends_on:
      - c2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  legit-client:
    build: ./legit_client
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "traefik:host-gateway"