apiVersion: apps/v1
kind: Deployment # pravi i nadgleda podove
metadata:
  name: detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detection
  template:
    metadata:
      labels:
        app: detection
    spec:
      containers:
        - name: detection
          image: detection:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe: 
            httpGet:      
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: detection
spec:
  selector:
    app: detection
  ports:
    - port: 8000
      targetPort: 8000