apiVersion: apps/v1
kind: Deployment # pravi i nadgleda podove
metadata:
  name: target
spec:
  replicas: 1
  selector:
    matchLabels: # njegovi podovi su oni koji imaju target labele
      app: target
  template:
    metadata:
      labels:
        app: target
    spec: # odnosi se na konkretan pod
      containers:
        - name: target
          image: target:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: GUNICORN_WORKERS
              value: "4"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe: # ready ili notready
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 5
            failureThreshold: 12 # potom service prestaje da salje saobracaj, pod je i dalje ziv
          livenessProbe: # jel ziv
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 10
            failureThreshold: 15 # potom k3s ubija i restaruje pod

---

apiVersion: v1
kind: Service
metadata:
  name: target
spec:
  selector:
    app: target
  ports:
    - port: 80
      targetPort: 5000