apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: target-ratelimit
spec:
  rateLimit:
    average: 10         
    period: 1s
    burst: 10            
    sourceCriterion:
      ipStrategy: {}