apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=120s"
      - "--entrypoints.web.transport.respondingTimeouts.idleTimeout=120s"
    hostNetwork: true
    deployment:
      kind: DaemonSet
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    ports:
      web:
        port: 80
    podSecurityContext:
      runAsNonRoot: false     
      runAsUser: 0             
      runAsGroup: 0            
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
        add: ["NET_BIND_SERVICE"]   
    service:
      spec:
        type: ClusterIP
    metrics:
      prometheus: {}
    logs:
      access:
        enabled: true